/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bill_transfer.java
 *
 * Created on Mar 28, 2012, 2:00:52 PM
 */

package securebilling;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import javax.swing.JFrame;
import java.io.*;

/**
 *
 * @author Admin
 */
public class bill_transfer extends javax.swing.JFrame {

    /** Creates new form bill_transfer */
    public String clientip, serverip;
    public String serversignature, clientsignature;
    public static String overalltime;
    public static JFrame frame;
    public static float bill;
    public bill_transfer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "BILL STATUS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Client IP :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 40, 110, 20);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(180, 40, 130, 23);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jPanel2.add(jTextField2);
        jTextField2.setBounds(180, 70, 130, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Client Signature :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 70, 110, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Server IP :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 100, 110, 20);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(180, 100, 130, 23);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        jTextField4.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField4InputMethodTextChanged(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(180, 130, 130, 23);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Server Signature :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 130, 120, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Billing Amount : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 190, 120, 20);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(180, 160, 130, 23);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Overall Time :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 160, 120, 20);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6);
        jTextField6.setBounds(180, 190, 130, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 100, 350, 270);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/transfer-bill.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 380, 160, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/server_back.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 510, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        clientip = jTextField1.getText();
      
        String driver = "com.mysql.jdbc.Driver";
        try
        {
            Class.forName(driver);
            Connection connect = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cns","root","");
            Statement state = (Statement) connect.createStatement();
            System.out.println(clientip);
            String sql = "SELECT clientsignature FROM signatures WHERE clientip = '"+clientip+"'";
            ResultSet rs = state.executeQuery(sql);
            while(rs.next())
            {
                clientsignature=rs.getString(1);
                System.out.println(clientsignature);
                jTextField2.setText(clientsignature);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        serverip = jTextField1.getText();
        
        String driver = "com.mysql.jdbc.Driver";
        try
        {
            Class.forName(driver);
            Connection connect = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cns","root","");
            Statement state = (Statement) connect.createStatement();
            String sql = "SELECT serversignature FROM signatures WHERE serverip = '"+serverip+"'";
            ResultSet rs = state.executeQuery(sql);
            while(rs.next())
            {
                serversignature=rs.getString(1);
                System.out.println(serversignature);
                jTextField4.setText(serversignature);
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField4InputMethodTextChanged
        // TODO add your handling code here:'[
        
    }//GEN-LAST:event_jTextField4InputMethodTextChanged

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        // TODO add your handling code here:
        
        String driver = "com.mysql.jdbc.Driver";
        try
        {
            Class.forName(driver);
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cns","root","");
            Statement stat = (Statement) conn.createStatement();
            String sql = "SELECT * FROM time";
            ResultSet rss = stat.executeQuery(sql);
            while(rss.next())
            {
                overalltime = rss.getString(3);
                System.out.println(overalltime);
                jTextField5.setText(overalltime);
            }


        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
        int hour,min,sec;
        float min1,hour1,sec1;
        StringTokenizer st = new StringTokenizer(overalltime,":");
        hour = Integer.parseInt(st.nextToken());
        hour1 = (float) (hour * 0.5);
        System.out.println(hour1);
        min = Integer.parseInt(st.nextToken());
        min1 = (float) (min * 1.5);
        System.out.println(min1);
        sec = Integer.parseInt(st.nextToken());
        sec1 = sec*2;
        System.out.println(sec1);
        bill = hour1+min1+sec1;
        jTextField6.setText("Rs."+bill);
//       while(st.hasMoreTokens())
//       {
//           String sq = st.nextToken();
//           String sq1 = st.nextToken();
//           String sq2 = st.nextToken();
//           System.out.println(sq+" "+sq1+" "+sq2);
//       }
        
    }//GEN-LAST:event_jTextField5FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            BufferedWriter bw = new BufferedWriter(new FileWriter("E:\\bill_status.txt"));
            bw.write("SERVER IP: "+serverip);
            bw.newLine();
            bw.write("SERVER SIGNATURE: "+serversignature);
            bw.newLine();
            bw.write("CLIENT IP: "+clientip);
            bw.newLine();
            bw.write("CLIENT SIGNATURE: "+clientsignature);
            bw.newLine();
            bw.write("SERVICE ACCESSING TIME: "+overalltime);
            bw.newLine();
            bw.write("BILL AMOUNT : Rs."+bill);
            bw.newLine();
            bw.close();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        File f = new File("E:\\bill_status.txt");
        f.delete();
    }//GEN-LAST:event_formWindowOpened

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill_transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
