/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * signature_cloud.java
 *
 * Created on Mar 26, 2012, 11:27:11 AM
 */

package securebilling;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.net.*;
import java.io.*;
import java.sql.DriverManager;
/**
 *
 * @author Admin
 */
public class signature_cloud extends javax.swing.JFrame {

    /** Creates new form signature_cloud */
    public String serverip,serversignature,clientip,clientsignature;
    public signature_cloud() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGNATURE_CLOUD");

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/record-signatures.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 340, 160, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/get-signatures.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 340, 150, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cloud Signature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Server IP :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 40, 100, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Server Signature :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 70, 130, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Client IP :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 100, 130, 20);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jPanel2.add(jTextField4);
        jTextField4.setBounds(180, 130, 120, 20);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jPanel2.add(jTextField3);
        jTextField3.setBounds(180, 100, 120, 20);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jPanel2.add(jTextField2);
        jTextField2.setBounds(180, 70, 120, 20);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jPanel2.add(jTextField1);
        jTextField1.setBounds(180, 40, 120, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Client Signature :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 130, 150, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 150, 330, 180);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Secure Billing Transactions in the Cloud Computing Environment");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 40, 480, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/server_back.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 510, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try
        {
            ServerSocket from_cns = new ServerSocket(789);
            while(true)
            {
                Socket from_cnsclient = from_cns.accept();
                BufferedReader buffread = new BufferedReader(new InputStreamReader(from_cnsclient.getInputStream()));
                serverip = buffread.readLine();
                System.out.println(serverip);
                jTextField1.setText(serverip);
                serversignature = buffread.readLine();
                System.out.println(serversignature);
                jTextField2.setText(serversignature);
                clientip = buffread.readLine();
                System.out.println(clientip);
                jTextField3.setText(clientip);
                clientsignature = buffread.readLine();
                System.out.println(clientsignature);
                jTextField4.setText(clientsignature);
                buffread.close();
                from_cns.close();
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String driver = "com.mysql.jdbc.Driver";
        try
        {
            Class.forName(driver);
            Connection cloudconnect = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/secure_billing","root","");
            Statement cloudstate = (Statement) cloudconnect.createStatement();
            String sql = "INSERT INTO signatures VALUES('"+serverip+"','"+serversignature+"','"+clientip+"','"+clientsignature+"')";
            cloudstate.executeUpdate(sql);
            System.out.println("INSERTED");
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        sendapp sp = new sendapp();
        sp.sendapp1();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signature_cloud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables


    class sendapp
{
     void sendapp1()
    {
        try
        {
            ServerSocket ss=new ServerSocket(100);
            Socket s=ss.accept();
            FileInputStream fis=new FileInputStream("C:\\Student\\Student\\dist\\Student.jar");
            int len=1;
            byte[] bytes=new byte[1024];
            BufferedOutputStream bos=new BufferedOutputStream(s.getOutputStream());
            while(len>0)
            {
                len=fis.read(bytes);
                if(len>0)
                {
                    bos.write(bytes,0,len);
                }
            }
            bos.close();
        }catch(Exception e){}
    }
}

}
